### PR TITLE
Drop Emacs 24.3 support

### LINKED ISSUE #165: Drop Emacs 24.3 support
It's almost [3 years old](http://lists.gnu.org/archive/html/info-gnu-emacs/2013-03/msg00001.html) and even [Debian stable](https://packages.debian.org/jessie/emacs24) thinks it's old. And because of Emacs 24.3 we have to keep [these ugly things](https://github.com/codingteam/pacmacs.el/blob/d608708f154fbcbd4a36b390893f1acb628bce82/pacmacs.el#L161) in our code base.

Maybe it's time to drop it?

@ForNeVeR, @Minoru, we already discussed that on the stream a bit. What do you guys think? I'm ok with dropping that ancient peace of crap.

### PR DESCRIPTION
**Pull request by rexim**
Close #165

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I approve this PR conditionally. If the coverage decrease is not a problem, then the PR is approved.

**Comment by rexim** [comment]
Alright, thank you Mr @ForNeVeR.

Actually [the comment](https://github.com/codingteam/pacmacs.el/issues/165#issuecomment-158753779) of Mr @Minoru made me think about this decision one more time. Maybe two argumented comparators is really not the reason for dropping the entire version completely.

I need to think about it more. Will update the issue and PR soon.

**Comment by rexim** [comment]
The latest decision is to drop the support anyway

**Comment by rexim** [comment]
I think we should not care about the coverage in this case. The only way to increase the coverage is to write a UT to something irrelevant to the PR which is stupid.

I'm merging the PR and officially dropping the Emacs 24.3 support.

**Comment by Minoru** [comment]
> I'm […] officially dropping the Emacs 24.3 support.

I'm unofficially picking it up, blow the bits of muck from it and set it
on the shelf. Old heroes should have their rest, properly.

:P

**Comment by ForNeVeR** [comment]
i am fornever

**Comment by rexim** [comment]
@Minoru feel free to fork the repo and backport all the future changes. ;)

**Pull request merged**
