### PR TITLE
Customize level folder

### LINKED ISSUE #191: Customization for level folder
List (and sequence) of game levels should be customizable through standard emacs customization mechanism.

### PR DESCRIPTION
**Pull request by rexim**
Close #191

### CODE REVIEW

**Comment by rexim** [comment]
Do not merge until https://github.com/milkypostman/melpa/pull/3477 is merged

**Comment by milkypostman** [comment]
does this have the OK to move forward? Think best is when this gets the OK then we'll merge the recipe change.

**Comment by ForNeVeR** [comment]
Yes, that is okay.

**Comment by milkypostman** [comment]
confused. this PR has the OK or OK to wait til you get a chance to review?

**Comment by ForNeVeR** [comment]
Review is done, this PR has my approval. Sorry for confusion :)

**Comment by milkypostman** [comment]
ok merged melpa change.  thanks!

**Comment by rexim** [comment]
Thank you @ForNeVeR and @milkypostman :)

**Pull request merged**
