### PR TITLE
Terrify/unterrify ghost without losing state

### LINKED ISSUE #171: Unterrified ghost loses its original possition
Thus cannot be reset.

### PR DESCRIPTION
**Pull request by rexim**
Close #171, #170

### CODE REVIEW

**Comment by ForNeVeR** [comment]
LGTM :+1:

**Comment by rexim** [comment]
Thanks!

**Comment by rexim** [comment]
Linux:
- ATT before: `0.007924s`
- ATT after: `0.007732s`

**Comment by rexim** [comment]
Windows:
- ATT before: `0.016067s`
- ATT after: `0.017342s`

**Pull request merged**
