### PR TITLE
Bump the copyright year for all the files

### PR DESCRIPTION
**Pull request by rexim**
Happy New Ear!

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I have a complaint here. Should it be `2015–2016` or just `2016`? Let's elaborate a bit.

**Comment by ForNeVeR** [comment]
Both [dash](https://github.com/magnars/dash.el/blob/master/dash-functional.el#L3) and [magit](https://github.com/magit/magit/blob/master/lisp/magit-bisect.el#L3) (as examples of the most popular melpa packages) seem to follow the year diapason notation in their sources. Let's use the same idea. Please change that to `2015-2016` (with simple dash without Unicode beauty, again, because guys seems to stick with ASCII for good measure).

**Comment by rexim** [comment]
Alright, sounds good to me. Let me change that then.

**Comment by rexim** [comment]
@ForNeVeR done

**Comment by ForNeVeR** [comment]
:+1:
My new :ear: is happy.

**Comment by rexim** [comment]
@ForNeVeR awesome! :)

**Pull request merged**
